#!/usr/bin/env python3
"""
Cross-platform installer for source-of-truth-agent-tool.

What it does (idempotent):
  1. Resolves the install dir at ~/.claude/skills/source-of-truth-agent-tool/.
     (Putting it under skills/ means Claude Code auto-discovers SKILL.md.)
  2. Copies the entire repo's contents (source_of_truth/ package, SKILL.md,
     project-start-wizard.md, README.md, etc.) into the install dir.
     EDGE CASE: if the user already cloned directly into the install dir
     and is running install.py from there, the copy step is silently
     skipped -- nothing to copy.
  3. Writes two wrapper scripts in the install dir:
       - user_prompt_submit_hook.py
       - post_tool_use_hook.py
     Each adds the install dir to sys.path and calls into the source_of_truth
     package next to it. On any error they silently emit {} so unrelated
     sessions never see import errors.
  4. Patches ~/.claude/settings.json to register both hooks if not already
     present. Existing hook entries are left untouched. Backed up first.
  5. Initializes ~/.source-of-truth/ with default global-settings.json.

Run:
  python3 install.py           # Linux/macOS
  python install.py            # Windows
"""
import datetime
import json
import os
import platform
import shutil


SKILL_INSTALL_DIR_NAME = "source-of-truth-agent-tool"
USER_PROMPT_SUBMIT_HOOK_FILENAME = "user_prompt_submit_hook.py"
POST_TOOL_USE_HOOK_FILENAME = "post_tool_use_hook.py"
ASKUSERQUESTION_CAPTURE_HOOK_FILENAME = "post_tool_use_askuserquestion_capture_hook.py"
WHAT_IS_SESSION_HOOK_FILENAME = "what_is_session_id_hook.py"
WHAT_IS_SESSION_SENTINEL_FILENAME = "WhatIsTheCurrentSessionId.txt"
WHAT_IS_SESSION_SENTINEL_STRING = "WhatIsTheCurrentSessionId"

USER_PROMPT_SUBMIT_HOOK_TEMPLATE = '''\
#!/usr/bin/env python3
"""Auto-generated by source-of-truth-agent-tool install.py."""
import sys
PACKAGE_DIRECTORY_ABSOLUTE_PATH = {package_dir!r}
def _emit_empty_and_exit_silently():
    print("{{}}")
    sys.exit(0)
def _main():
    try:
        sys.path.insert(0, PACKAGE_DIRECTORY_ABSOLUTE_PATH)
        from source_of_truth.cli_entrypoint import _handle_user_prompt_submit_hook
    except Exception:
        _emit_empty_and_exit_silently(); return
    try:
        sys.exit(_handle_user_prompt_submit_hook())
    except Exception:
        _emit_empty_and_exit_silently()
if __name__ == "__main__":
    _main()
'''

WHAT_IS_SESSION_HOOK_TEMPLATE = '''\
#!/usr/bin/env python3
"""Auto-generated by source-of-truth-agent-tool install.py.

Standalone PostToolUse hook. Does nothing unless the tool_input of the
just-completed tool call contains the sentinel string {sentinel_string!r}.
When it does, emit a hookSpecificOutput that surfaces the current session_id
to both the user (as systemMessage) and the agent (as additionalContext).

Self-contained: no imports from source_of_truth package, so it works even
if that package is broken or absent. On any error, silently emit {{}} so
unrelated sessions never see noise.
"""
import json
import sys

SENTINEL_SUBSTRING = {sentinel_string!r}


def _emit_empty_and_exit_silently():
    print("{{}}")
    sys.exit(0)


def _tool_input_mentions_sentinel(tool_input_value):
    try:
        serialized_form = json.dumps(tool_input_value, ensure_ascii=False)
    except Exception:
        serialized_form = str(tool_input_value)
    return SENTINEL_SUBSTRING in serialized_form


def _main():
    try:
        raw_stdin_payload = sys.stdin.read()
        if not raw_stdin_payload.strip():
            _emit_empty_and_exit_silently(); return
        hook_event_payload = json.loads(raw_stdin_payload)
    except Exception:
        _emit_empty_and_exit_silently(); return

    tool_input_value = hook_event_payload.get("tool_input")
    if tool_input_value is None or not _tool_input_mentions_sentinel(tool_input_value):
        _emit_empty_and_exit_silently(); return

    current_session_id = hook_event_payload.get("session_id", "<unknown>")
    user_visible_and_agent_visible_message = f"Current session id: {{current_session_id}}"

    response_payload_for_claude_code = {{
        "hookSpecificOutput": {{
            "hookEventName": "PostToolUse",
            "additionalContext": user_visible_and_agent_visible_message,
        }},
        "systemMessage": user_visible_and_agent_visible_message,
    }}
    print(json.dumps(response_payload_for_claude_code))
    sys.exit(0)


if __name__ == "__main__":
    try:
        _main()
    except Exception:
        _emit_empty_and_exit_silently()
'''

POST_TOOL_USE_HOOK_TEMPLATE = '''\
#!/usr/bin/env python3
"""Auto-generated by source-of-truth-agent-tool install.py."""
import sys
PACKAGE_DIRECTORY_ABSOLUTE_PATH = {package_dir!r}
def _emit_empty_and_exit_silently():
    print("{{}}")
    sys.exit(0)
def _main():
    try:
        sys.path.insert(0, PACKAGE_DIRECTORY_ABSOLUTE_PATH)
        from source_of_truth.post_tool_use_show_messages_to_raw_input_sender import _main as inner_main
    except Exception:
        _emit_empty_and_exit_silently(); return
    try:
        sys.exit(inner_main())
    except Exception:
        _emit_empty_and_exit_silently()
if __name__ == "__main__":
    _main()
'''


ASKUSERQUESTION_CAPTURE_HOOK_TEMPLATE = '''\
#!/usr/bin/env python3
"""Auto-generated by source-of-truth-agent-tool install.py."""
import sys
PACKAGE_DIRECTORY_ABSOLUTE_PATH = {package_dir!r}
def _emit_empty_and_exit_silently():
    print("{{}}")
    sys.exit(0)
def _main():
    try:
        sys.path.insert(0, PACKAGE_DIRECTORY_ABSOLUTE_PATH)
        from source_of_truth.post_tool_use_capture_askuserquestion_answers import _main as inner_main
    except Exception:
        _emit_empty_and_exit_silently(); return
    try:
        sys.exit(inner_main())
    except Exception:
        _emit_empty_and_exit_silently()
if __name__ == "__main__":
    _main()
'''


def home_claude_dir():
    return os.path.expanduser("~/.claude")


def home_skills_dir():
    return os.path.join(home_claude_dir(), "skills")


def install_dir_path():
    return os.path.join(home_skills_dir(), SKILL_INSTALL_DIR_NAME)


def settings_json_path():
    return os.path.join(home_claude_dir(), "settings.json")


def python_launcher_for_current_platform():
    return "python" if platform.system() == "Windows" else "python3"


def is_running_from_install_dir(repo_dir, install_dir):
    return os.path.realpath(repo_dir) == os.path.realpath(install_dir)


def back_up_existing_install_dir_by_moving_it(install_dir):
    """Move an existing install dir to a timestamped backup, never delete it.

    Backup location:
        ~/.claude/source-of-truth-bak/<UTC-timestamp>/source-of-truth-agent-tool/

    This makes a reinstall non-destructive by default: the whole old folder
    (including anything a user may have placed in it) is preserved, not wiped.
    Returns the backup path, or None if there was no existing dir to move.
    """
    if not os.path.isdir(install_dir):
        return None
    timestamp = datetime.datetime.utcnow().strftime("%Y%m%dT%H%M%SZ")
    backup_parent_dir = os.path.join(home_claude_dir(), "source-of-truth-bak", timestamp)
    backup_dir = os.path.join(backup_parent_dir, SKILL_INSTALL_DIR_NAME)
    os.makedirs(backup_parent_dir, exist_ok=True)
    shutil.move(install_dir, backup_dir)
    return backup_dir


def copy_repo_contents_into_install_dir(repo_dir, install_dir):
    """Deploy the repo into the install dir.

    Skips .git/, .claude/, __pycache__/, *.pyc, and any *.bak* settings backups
    that might happen to be under the repo (defensive). .claude/ is session-local
    Claude Code state (settings, plans, hooks) -- never part of the deployable
    tool. Any existing install dir is NOT deleted -- it is moved to a timestamped
    backup first (so renamed/removed files don't linger AND nothing is ever
    destroyed), then the repo is copied in fresh.
    """
    ignore_patterns_callable = shutil.ignore_patterns(
        ".git", ".claude", "__pycache__", "*.pyc", "*.bak.*",
    )
    backup_dir = back_up_existing_install_dir_by_moving_it(install_dir)
    if backup_dir:
        print(
            "  NOTE: existing install dir preserved (not deleted); moved to backup:\n"
            f"    {backup_dir}"
        )
    shutil.copytree(repo_dir, install_dir, ignore=ignore_patterns_callable)
    print(f"  copied repo -> {install_dir}")


def load_or_init_settings_json(path):
    if not os.path.isfile(path):
        return {}
    with open(path) as f:
        content = f.read().strip()
    return json.loads(content) if content else {}


def remove_stale_source_of_truth_hook_entries(
    settings_data, hook_event_name, install_dir_canonical
):
    """Remove any pre-existing hook entries that mention SKILL_INSTALL_DIR_NAME
    but do NOT point at the current install_dir. This is the duplicate-prevention
    guard: install.py never adds an entry alongside a stale one for the same tool.

    Returns count of removed entries.
    """
    hooks_root = settings_data.get("hooks")
    if not isinstance(hooks_root, dict):
        return 0
    event_list = hooks_root.get(hook_event_name)
    if not isinstance(event_list, list):
        return 0
    removed_count = 0
    surviving_matcher_entries = []
    for matcher_entry in event_list:
        inner_hooks = matcher_entry.get("hooks", [])
        filtered_inner_hooks = []
        for hook_item in inner_hooks:
            command_text = hook_item.get("command", "")
            mentions_our_tool = SKILL_INSTALL_DIR_NAME in command_text
            points_at_current_install = install_dir_canonical in command_text
            if mentions_our_tool and not points_at_current_install:
                removed_count += 1
                continue
            filtered_inner_hooks.append(hook_item)
        if filtered_inner_hooks:
            matcher_entry["hooks"] = filtered_inner_hooks
            surviving_matcher_entries.append(matcher_entry)
    if surviving_matcher_entries:
        hooks_root[hook_event_name] = surviving_matcher_entries
    else:
        hooks_root.pop(hook_event_name, None)
        if not hooks_root:
            settings_data.pop("hooks", None)
    return removed_count


def remove_all_source_of_truth_hook_entries_for_event(settings_data, hook_event_name):
    """Remove EVERY hook entry for an event that mentions this tool, regardless of
    path. Used to retire a hook event the tool no longer uses (the Stop hook).
    Returns the count of removed entries."""
    hooks_root = settings_data.get("hooks")
    if not isinstance(hooks_root, dict):
        return 0
    event_list = hooks_root.get(hook_event_name)
    if not isinstance(event_list, list):
        return 0
    removed_count = 0
    surviving_matcher_entries = []
    for matcher_entry in event_list:
        kept_inner_hooks = []
        for hook_item in matcher_entry.get("hooks", []):
            if SKILL_INSTALL_DIR_NAME in hook_item.get("command", ""):
                removed_count += 1
                continue
            kept_inner_hooks.append(hook_item)
        if kept_inner_hooks:
            matcher_entry["hooks"] = kept_inner_hooks
            surviving_matcher_entries.append(matcher_entry)
    if surviving_matcher_entries:
        hooks_root[hook_event_name] = surviving_matcher_entries
    else:
        hooks_root.pop(hook_event_name, None)
        if not hooks_root:
            settings_data.pop("hooks", None)
    return removed_count


def hook_event_already_has_entry_for_install_dir(settings_data, hook_event_name, install_dir_canonical):
    entries = settings_data.get("hooks", {}).get(hook_event_name, [])
    for matcher_entry in entries:
        for hook_item in matcher_entry.get("hooks", []):
            if install_dir_canonical in hook_item.get("command", ""):
                return True
    return False


def append_hook_entry(settings_data, hook_event_name, matcher, command):
    hooks_root = settings_data.setdefault("hooks", {})
    event_list = hooks_root.setdefault(hook_event_name, [])
    event_list.append({
        "matcher": matcher,
        "hooks": [{"type": "command", "command": command}],
    })


def backup_file(path):
    if not os.path.isfile(path):
        return None
    timestamp = datetime.datetime.utcnow().strftime("%Y%m%dT%H%M%SZ")
    backup_path = f"{path}.bak.{timestamp}"
    shutil.copyfile(path, backup_path)
    return backup_path


def write_settings_json(path, data):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        json.dump(data, f, indent=2)
        f.write("\n")


def write_wrapper_scripts(install_dir):
    os.makedirs(install_dir, exist_ok=True)
    user_hook_path = os.path.join(install_dir, USER_PROMPT_SUBMIT_HOOK_FILENAME)
    post_hook_path = os.path.join(install_dir, POST_TOOL_USE_HOOK_FILENAME)
    askuserquestion_capture_hook_path = os.path.join(install_dir, ASKUSERQUESTION_CAPTURE_HOOK_FILENAME)
    what_is_session_hook_path = os.path.join(install_dir, WHAT_IS_SESSION_HOOK_FILENAME)
    sentinel_txt_path = os.path.join(install_dir, WHAT_IS_SESSION_SENTINEL_FILENAME)

    with open(user_hook_path, "w") as f:
        f.write(USER_PROMPT_SUBMIT_HOOK_TEMPLATE.format(package_dir=install_dir))
    with open(post_hook_path, "w") as f:
        f.write(POST_TOOL_USE_HOOK_TEMPLATE.format(package_dir=install_dir))
    with open(askuserquestion_capture_hook_path, "w") as f:
        f.write(ASKUSERQUESTION_CAPTURE_HOOK_TEMPLATE.format(package_dir=install_dir))
    with open(what_is_session_hook_path, "w") as f:
        f.write(WHAT_IS_SESSION_HOOK_TEMPLATE.format(
            sentinel_string=WHAT_IS_SESSION_SENTINEL_STRING,
        ))
    with open(sentinel_txt_path, "w", encoding="utf-8") as f:
        f.write(
            "If source-of-truth is installed, its hook will echo the "
            "current session id to the user notification and the "
            "additionalContext whenever a tool call's input mentions the "
            "string WhatIsTheCurrentSessionId. Read or cat this file to "
            "trigger that.\n"
        )

    if platform.system() != "Windows":
        os.chmod(user_hook_path, 0o755)
        os.chmod(post_hook_path, 0o755)
        os.chmod(askuserquestion_capture_hook_path, 0o755)
        os.chmod(what_is_session_hook_path, 0o755)
    print(f"  wrote: {user_hook_path}")
    print(f"  wrote: {post_hook_path}")
    print(f"  wrote: {askuserquestion_capture_hook_path}")
    print(f"  wrote: {what_is_session_hook_path}")
    print(f"  wrote: {sentinel_txt_path}")
    return user_hook_path, post_hook_path, what_is_session_hook_path


SOURCE_OF_TRUTH_WRAPPER_SCRIPT_NAME_POSIX = "source-of-truth"
SOURCE_OF_TRUTH_WRAPPER_SCRIPT_NAME_WINDOWS = "source-of-truth.bat"

POSIX_SKILL_FOLDER_WRAPPER_TEMPLATE = '''\
#!/usr/bin/env bash
# Auto-generated by source-of-truth-agent-tool install.py.
# Thin wrapper that forwards every arg to the cli_entrypoint dispatcher.
exec python3 -c "import sys; sys.path.insert(0, {install_dir_quoted}); from source_of_truth.cli_entrypoint import _main; sys.exit(_main())" "$@"
'''

WINDOWS_SKILL_FOLDER_WRAPPER_TEMPLATE = '''\
@echo off
REM Auto-generated by source-of-truth-agent-tool install.py.
REM Thin wrapper that forwards every arg to the cli_entrypoint dispatcher.
python -c "import sys; sys.path.insert(0, {install_dir_quoted}); from source_of_truth.cli_entrypoint import _main; sys.exit(_main())" %*
'''

POSIX_PATH_STUB_TEMPLATE = '''\
#!/usr/bin/env bash
# Auto-generated by source-of-truth-agent-tool install.py.
# Forwards to the canonical wrapper inside the skill folder.
exec {skill_folder_wrapper_quoted} "$@"
'''

WINDOWS_PATH_STUB_TEMPLATE = '''\
@echo off
REM Auto-generated by source-of-truth-agent-tool install.py.
REM Forwards to the canonical wrapper inside the skill folder.
call {skill_folder_wrapper_quoted} %*
'''


def write_skill_folder_source_of_truth_wrapper(install_dir):
    """Write the canonical `source-of-truth` wrapper script inside the skill folder.

    This is the script the PATH stub forwards to. Lives next to the package code
    so the skill folder is fully self-contained.
    """
    if platform.system() == "Windows":
        wrapper_filename = SOURCE_OF_TRUTH_WRAPPER_SCRIPT_NAME_WINDOWS
        template = WINDOWS_SKILL_FOLDER_WRAPPER_TEMPLATE
    else:
        wrapper_filename = SOURCE_OF_TRUTH_WRAPPER_SCRIPT_NAME_POSIX
        template = POSIX_SKILL_FOLDER_WRAPPER_TEMPLATE
    wrapper_path = os.path.join(install_dir, wrapper_filename)
    with open(wrapper_path, "w") as f:
        f.write(template.format(install_dir_quoted=repr(install_dir)))
    if platform.system() != "Windows":
        os.chmod(wrapper_path, 0o755)
    print(f"  wrote skill-folder wrapper -> {wrapper_path}")
    return wrapper_path


def path_stub_target_directory_for_current_platform():
    """Return the dir where install.py should write the on-PATH stub.

    Linux/macOS: ~/.local/bin (Python community convention; usually on PATH).
    Windows:    %USERPROFILE%\\AppData\\Local\\Microsoft\\WindowsApps
                (per-user, on PATH by default in Windows 10+, no admin rights).
    """
    if platform.system() == "Windows":
        return os.path.join(
            os.path.expanduser("~"),
            "AppData", "Local", "Microsoft", "WindowsApps",
        )
    return os.path.join(os.path.expanduser("~"), ".local", "bin")


def write_path_stub_forwarding_to_skill_folder_wrapper(skill_folder_wrapper_path):
    """Write a tiny stub on PATH that forwards to the skill-folder wrapper.

    Returns (stub_path, target_dir_was_already_on_PATH).
    """
    target_dir = path_stub_target_directory_for_current_platform()
    os.makedirs(target_dir, exist_ok=True)
    if platform.system() == "Windows":
        stub_filename = SOURCE_OF_TRUTH_WRAPPER_SCRIPT_NAME_WINDOWS
        template = WINDOWS_PATH_STUB_TEMPLATE
        # cmd.exe does not honor single quotes; wrap with double quotes instead.
        wrapper_quoted = '"' + skill_folder_wrapper_path.replace('"', '""') + '"'
    else:
        stub_filename = SOURCE_OF_TRUTH_WRAPPER_SCRIPT_NAME_POSIX
        template = POSIX_PATH_STUB_TEMPLATE
        wrapper_quoted = repr(skill_folder_wrapper_path)
    stub_path = os.path.join(target_dir, stub_filename)
    with open(stub_path, "w", encoding="utf-8") as f:
        f.write(template.format(skill_folder_wrapper_quoted=wrapper_quoted))
    if platform.system() != "Windows":
        os.chmod(stub_path, 0o755)
    print(f"  wrote PATH stub -> {stub_path}")

    # Best-effort PATH check.
    path_environment_value = os.environ.get("PATH", "")
    path_separator_for_platform = ";" if platform.system() == "Windows" else ":"
    on_path_already = os.path.realpath(target_dir) in [
        os.path.realpath(p) for p in path_environment_value.split(path_separator_for_platform)
        if p
    ]
    if not on_path_already:
        print(
            f"  NOTE: {target_dir} is not currently on your PATH. "
            "Add it to invoke `source-of-truth` from anywhere; "
            "otherwise call the skill-folder wrapper directly."
        )
    return stub_path


def initialize_global_settings_file():
    """Create ~/.source-of-truth/global-settings.json with defaults if absent."""
    sot_root = os.path.expanduser("~/.source-of-truth")
    global_settings_path = os.path.join(sot_root, "global-settings.json")
    os.makedirs(sot_root, exist_ok=True)
    os.makedirs(os.path.join(sot_root, "projects"), exist_ok=True)
    if os.path.isfile(global_settings_path):
        print(f"  global settings already present at {global_settings_path}")
        return
    default_payload = {
        "reviewer_command": ["claude", "-p"],
        "reviewer_mode": "live",
        "reviewer_model_name": "claude-haiku-4-5-20251001",
    }
    with open(global_settings_path, "w") as f:
        json.dump(default_payload, f, indent=2, sort_keys=True)
        f.write("\n")
    print(f"  wrote default global settings -> {global_settings_path}")


def ensure_settings_json_hook_entries(install_dir, settings_path, python_launcher):
    """Idempotently ensure ~/.claude/settings.json has the four SoT hook entries
    pointing at install_dir; scrub stale entries pointing elsewhere. Returns True
    if settings.json was modified. Reused by main() and the register-time health
    check, so the hook-registration logic lives in exactly one place."""
    user_hook_path = os.path.join(install_dir, USER_PROMPT_SUBMIT_HOOK_FILENAME)
    post_hook_path = os.path.join(install_dir, POST_TOOL_USE_HOOK_FILENAME)
    askuserquestion_capture_hook_path = os.path.join(install_dir, ASKUSERQUESTION_CAPTURE_HOOK_FILENAME)
    what_is_session_hook_path = os.path.join(install_dir, WHAT_IS_SESSION_HOOK_FILENAME)

    settings_data = load_or_init_settings_json(settings_path)
    user_command = f'{python_launcher} "{user_hook_path}"'
    post_command = f'{python_launcher} "{post_hook_path}"'
    askuserquestion_capture_command = f'{python_launcher} "{askuserquestion_capture_hook_path}"'
    what_is_session_command = f'{python_launcher} "{what_is_session_hook_path}"'

    settings_was_modified = False

    # Duplicate-prevention guard: scrub any pre-existing entries that mention
    # this tool but do NOT point at the current install dir. Catches stale
    # entries from a previous install at a different path (e.g. an older
    # version of install.py that used a different layout).
    removed_user = remove_stale_source_of_truth_hook_entries(
        settings_data, "UserPromptSubmit", install_dir
    )
    removed_post = remove_stale_source_of_truth_hook_entries(
        settings_data, "PostToolUse", install_dir
    )
    if removed_user + removed_post:
        print(f"  removed {removed_user} stale UserPromptSubmit + "
              f"{removed_post} stale PostToolUse entries pointing elsewhere")
        settings_was_modified = True

    # Retire the old Stop hook entirely: pre-text is now captured by the
    # UserPromptSubmit hook (which fires even when a turn is interrupted), so the
    # Stop hook is obsolete. Remove ANY SoT Stop entry left from a prior install.
    removed_stop = remove_all_source_of_truth_hook_entries_for_event(settings_data, "Stop")
    if removed_stop:
        print(f"  removed {removed_stop} obsolete Stop entr(y/ies) "
              f"(pre-text capture moved to UserPromptSubmit)")
        settings_was_modified = True

    if hook_event_already_has_entry_for_install_dir(settings_data, "UserPromptSubmit", install_dir):
        print("  UserPromptSubmit entry already present -- no change")
    else:
        append_hook_entry(settings_data, "UserPromptSubmit", "*", user_command)
        print(f"  appended UserPromptSubmit: {user_command}")
        settings_was_modified = True

    # Two distinct PostToolUse hooks both point at install_dir, so
    # hook_event_already_has_entry_for_install_dir can't tell them apart.
    # Match each command explicitly instead.
    existing_post_commands_in_settings = [
        hook_item.get("command", "")
        for matcher_entry in settings_data.get("hooks", {}).get("PostToolUse", [])
        for hook_item in matcher_entry.get("hooks", [])
    ]
    if post_command not in existing_post_commands_in_settings:
        append_hook_entry(settings_data, "PostToolUse", "Bash", post_command)
        print(f"  appended PostToolUse(matcher=Bash): {post_command}")
        settings_was_modified = True
    else:
        print("  PostToolUse (SoT) entry already present -- no change")
    if askuserquestion_capture_command not in existing_post_commands_in_settings:
        append_hook_entry(settings_data, "PostToolUse", "AskUserQuestion", askuserquestion_capture_command)
        print(f"  appended PostToolUse(matcher=AskUserQuestion): {askuserquestion_capture_command}")
        settings_was_modified = True
    else:
        print("  PostToolUse (AskUserQuestion capture) entry already present -- no change")
    if what_is_session_command not in existing_post_commands_in_settings:
        append_hook_entry(settings_data, "PostToolUse", "*", what_is_session_command)
        print(f"  appended PostToolUse(matcher=*) what-is-session: {what_is_session_command}")
        settings_was_modified = True
    else:
        print("  PostToolUse (what-is-session) entry already present -- no change")

    if settings_was_modified:
        backup_path = backup_file(settings_path)
        if backup_path:
            print(f"  backed up old settings.json to {backup_path}")
        write_settings_json(settings_path, settings_data)
    else:
        print("  no settings.json changes needed")
    return settings_was_modified


def main():
    repo_dir = os.path.dirname(os.path.abspath(__file__))
    install_dir = install_dir_path()
    settings_path = settings_json_path()
    python_launcher = python_launcher_for_current_platform()

    print(f"Repo dir:    {repo_dir}")
    print(f"Install dir: {install_dir}")
    print(f"Settings:    {settings_path}\n")

    print("Step 1: deploy repo contents to install dir")
    if is_running_from_install_dir(repo_dir, install_dir):
        print(f"  running from install dir -- copy step skipped")
    else:
        os.makedirs(home_skills_dir(), exist_ok=True)
        copy_repo_contents_into_install_dir(repo_dir, install_dir)
    print()

    print("Step 2: write hook wrapper scripts in install dir")
    write_wrapper_scripts(install_dir)
    print()

    print("Step 3: update ~/.claude/settings.json")
    ensure_settings_json_hook_entries(install_dir, settings_path, python_launcher)
    print()

    print("Step 4: write `source-of-truth` wrapper inside skill folder")
    skill_folder_wrapper_path = write_skill_folder_source_of_truth_wrapper(install_dir)
    print()

    print("Step 5: deploy on-PATH `source-of-truth` stub forwarding to skill-folder wrapper")
    write_path_stub_forwarding_to_skill_folder_wrapper(skill_folder_wrapper_path)
    print()

    print("Step 6: initialize ~/.source-of-truth/ global settings")
    initialize_global_settings_file()

    print()
    print("=" * 60)
    print("INSTALL COMPLETE")
    print("=" * 60)
    print("What was done:")
    print(f"  - Skill files deployed to: {install_dir}")
    print(f"  - Hook wrappers written:")
    print(f"      * UserPromptSubmit (raw input capture + pre-text from transcript)")
    print(f"      * PostToolUse:Bash (SoT messages-to-user)")
    print(f"      * PostToolUse:AskUserQuestion (capture user's selected answers)")
    print(f"      * PostToolUse:* (what-is-session-id sentinel hook)")
    print(f"  - Sentinel file: WhatIsTheCurrentSessionId.txt")
    print(f"  - settings.json updated at: {settings_path}")
    print(f"  - `source-of-truth` PATH stub deployed.")
    print(f"  - Global settings ensured at: ~/.source-of-truth/global-settings.json")
    print()
    print("What's next:")
    print("  1. Start a NEW Claude Code session so the hooks load (existing")
    print("     sessions read settings.json at startup and won't pick up the")
    print("     new entries).")
    print("  2. In the new session, register your project with:")
    print("       source-of-truth init-and-register <session_id> <jsonl_path>")
    print("     The SKILL will walk you through it -- ask the agent to start")
    print("     the source-of-truth setup wizard.")
    print("  3. To remove later, run uninstall.py from this repo. It only")
    print("     removes hooks + PATH stub; the install folder stays put.")


if __name__ == "__main__":
    main()
