#!/usr/bin/env python3
"""
Cross-platform installer for source-of-truth-agent-tool's global hooks.

What it does (idempotent and re-runnable):
  1. Records the absolute path of THIS repo (where install.py lives) so the
     hook wrapper scripts know how to import the source_of_truth package.
  2. Creates ~/.claude/hooks/source-of-truth-agent-tool/ (the install dir).
  3. Writes two wrapper scripts there:
       - user_prompt_submit_hook.py
       - post_tool_use_hook.py
     Each does its own sys.path setup pointing at this repo, and silently
     emits {} on any error so unrelated sessions never see import errors.
  4. Reads ~/.claude/settings.json (creates an empty one if missing).
  5. If our UserPromptSubmit and PostToolUse(matcher=Bash) entries are not
     present, appends them. Existing hook entries (yours or other plugins')
     are preserved untouched.
  6. Writes settings.json back with a timestamped backup.
  7. Cleans up old install layouts: removes loose wrapper scripts at
     ~/.claude/hooks/source_of_truth_*_hook.py and any hook entries that
     reference them, so re-running this installer migrates an older manual
     install to the proper layout cleanly.

Run:
  python3 install.py           # Linux/macOS
  python install.py            # Windows
"""
import datetime
import json
import os
import platform
import shutil
import sys


HOOK_INSTALL_DIR_NAME = "source-of-truth-agent-tool"
USER_PROMPT_SUBMIT_HOOK_FILENAME = "user_prompt_submit_hook.py"
POST_TOOL_USE_HOOK_FILENAME = "post_tool_use_hook.py"

# Marker substrings used to identify our hook entries (and old-style loose
# wrappers) in settings.json so we can update or remove them on re-install.
NEW_INSTALL_DIR_MARKER_SUBSTRING = HOOK_INSTALL_DIR_NAME
OLD_LOOSE_WRAPPER_MARKER_SUBSTRINGS = (
    "source_of_truth_user_prompt_submit_hook.py",
    "source_of_truth_post_tool_use_hook.py",
)

USER_PROMPT_SUBMIT_HOOK_TEMPLATE = '''\
#!/usr/bin/env python3
"""Auto-generated by source-of-truth-agent-tool install.py. Do not edit by hand."""
import sys
PACKAGE_DIRECTORY_ABSOLUTE_PATH = {package_dir!r}
def _emit_empty_and_exit_silently():
    print("{{}}")
    sys.exit(0)
def _main():
    try:
        sys.path.insert(0, PACKAGE_DIRECTORY_ABSOLUTE_PATH)
        from source_of_truth.cli_entrypoint import _handle_user_prompt_submit_hook
    except Exception:
        _emit_empty_and_exit_silently(); return
    try:
        sys.exit(_handle_user_prompt_submit_hook())
    except Exception:
        _emit_empty_and_exit_silently()
if __name__ == "__main__":
    _main()
'''

POST_TOOL_USE_HOOK_TEMPLATE = '''\
#!/usr/bin/env python3
"""Auto-generated by source-of-truth-agent-tool install.py. Do not edit by hand."""
import sys
PACKAGE_DIRECTORY_ABSOLUTE_PATH = {package_dir!r}
def _emit_empty_and_exit_silently():
    print("{{}}")
    sys.exit(0)
def _main():
    try:
        sys.path.insert(0, PACKAGE_DIRECTORY_ABSOLUTE_PATH)
        from source_of_truth.post_tool_use_show_messages_to_raw_input_sender import _main as inner_main
    except Exception:
        _emit_empty_and_exit_silently(); return
    try:
        sys.exit(inner_main())
    except Exception:
        _emit_empty_and_exit_silently()
if __name__ == "__main__":
    _main()
'''


def home_claude_dir():
    return os.path.expanduser("~/.claude")


def install_dir_path():
    return os.path.join(home_claude_dir(), "hooks", HOOK_INSTALL_DIR_NAME)


def settings_json_path():
    return os.path.join(home_claude_dir(), "settings.json")


def python_launcher_for_current_platform():
    if platform.system() == "Windows":
        return "python"
    return "python3"


def write_wrapper_scripts(install_dir, package_dir):
    os.makedirs(install_dir, exist_ok=True)
    user_hook_destination = os.path.join(install_dir, USER_PROMPT_SUBMIT_HOOK_FILENAME)
    post_hook_destination = os.path.join(install_dir, POST_TOOL_USE_HOOK_FILENAME)
    with open(user_hook_destination, "w") as f:
        f.write(USER_PROMPT_SUBMIT_HOOK_TEMPLATE.format(package_dir=package_dir))
    with open(post_hook_destination, "w") as f:
        f.write(POST_TOOL_USE_HOOK_TEMPLATE.format(package_dir=package_dir))
    if platform.system() != "Windows":
        os.chmod(user_hook_destination, 0o755)
        os.chmod(post_hook_destination, 0o755)
    print(f"  wrote: {user_hook_destination}")
    print(f"  wrote: {post_hook_destination}")
    return user_hook_destination, post_hook_destination


def load_or_init_settings_json(path):
    if not os.path.isfile(path):
        print(f"  settings.json not found at {path} — will create")
        return {}
    with open(path) as f:
        content = f.read().strip()
    if not content:
        return {}
    return json.loads(content)


def hook_event_already_has_entry_referencing(settings_data, hook_event_name, marker_substrings):
    entries = settings_data.get("hooks", {}).get(hook_event_name, [])
    for matcher_entry in entries:
        for hook_item in matcher_entry.get("hooks", []):
            command_text = hook_item.get("command", "")
            if any(m in command_text for m in marker_substrings):
                return True
    return False


def append_hook_entry(settings_data, hook_event_name, matcher, command):
    hooks_root = settings_data.setdefault("hooks", {})
    event_list = hooks_root.setdefault(hook_event_name, [])
    event_list.append({
        "matcher": matcher,
        "hooks": [{"type": "command", "command": command}],
    })


def remove_hook_entries_matching_substrings(settings_data, hook_event_name, marker_substrings):
    """Returns count of removed entries. Mutates settings_data."""
    hooks_root = settings_data.get("hooks")
    if not isinstance(hooks_root, dict):
        return 0
    event_list = hooks_root.get(hook_event_name)
    if not isinstance(event_list, list):
        return 0
    removed_count = 0
    surviving_matcher_entries = []
    for matcher_entry in event_list:
        inner_hooks = matcher_entry.get("hooks", [])
        filtered_inner_hooks = []
        for hook_item in inner_hooks:
            command_text = hook_item.get("command", "")
            if any(m in command_text for m in marker_substrings):
                removed_count += 1
                continue
            filtered_inner_hooks.append(hook_item)
        if filtered_inner_hooks:
            matcher_entry["hooks"] = filtered_inner_hooks
            surviving_matcher_entries.append(matcher_entry)
    if surviving_matcher_entries:
        hooks_root[hook_event_name] = surviving_matcher_entries
    else:
        hooks_root.pop(hook_event_name, None)
        if not hooks_root:
            settings_data.pop("hooks", None)
    return removed_count


BACKWARD_COMPAT_FORWARDER_TEMPLATE = '''\
#!/usr/bin/env python3
"""Backward-compat forwarder. Already-running Claude Code sessions cached the
old hook command at startup pointing at this loose-wrapper path; the installer
has since moved the real wrapper into a dedicated install dir. This stub just
exec's the new one. Safe to delete once all old sessions have been restarted."""
import os
import sys
NEW_WRAPPER_PATH = os.path.expanduser({new_wrapper_path!r})
if os.path.isfile(NEW_WRAPPER_PATH):
    os.execv(sys.executable, [sys.executable, NEW_WRAPPER_PATH])
else:
    print("{{}}")
    sys.exit(0)
'''


def write_backward_compat_forwarder_stubs(install_dir):
    """Write thin stubs at the OLD loose-wrapper paths that exec the new wrappers.

    This keeps already-running sessions working after a re-install (their hook
    config was cached pointing at the old path; we replace the file in place
    rather than deleting it).
    """
    home_hooks_dir = os.path.join(home_claude_dir(), "hooks")
    forwarder_targets = (
        ("source_of_truth_user_prompt_submit_hook.py",
         os.path.join("~/.claude/hooks", HOOK_INSTALL_DIR_NAME, USER_PROMPT_SUBMIT_HOOK_FILENAME)),
        ("source_of_truth_post_tool_use_hook.py",
         os.path.join("~/.claude/hooks", HOOK_INSTALL_DIR_NAME, POST_TOOL_USE_HOOK_FILENAME)),
    )
    for old_filename, new_wrapper_user_path in forwarder_targets:
        forwarder_path = os.path.join(home_hooks_dir, old_filename)
        with open(forwarder_path, "w") as f:
            f.write(BACKWARD_COMPAT_FORWARDER_TEMPLATE.format(
                new_wrapper_path=new_wrapper_user_path
            ))
        if platform.system() != "Windows":
            os.chmod(forwarder_path, 0o755)
        print(f"  wrote backward-compat stub: {forwarder_path}")


def backup_file(path):
    if not os.path.isfile(path):
        return None
    timestamp = datetime.datetime.utcnow().strftime("%Y%m%dT%H%M%SZ")
    backup_path = f"{path}.bak.{timestamp}"
    shutil.copyfile(path, backup_path)
    return backup_path


def write_settings_json(path, data):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        json.dump(data, f, indent=2)
        f.write("\n")


def main():
    package_dir = os.path.dirname(os.path.abspath(__file__))
    install_dir = install_dir_path()
    settings_path = settings_json_path()
    python_launcher = python_launcher_for_current_platform()

    print(f"Platform:    {platform.system()}")
    print(f"Package dir: {package_dir}")
    print(f"Install dir: {install_dir}")
    print(f"Settings:    {settings_path}")
    print()

    print("Step 1: write hook wrapper scripts")
    user_hook_path, post_hook_path = write_wrapper_scripts(install_dir, package_dir)
    print()

    print("Step 2: update ~/.claude/settings.json")
    settings_data = load_or_init_settings_json(settings_path)

    # Migration: drop any old hook entries that referenced loose wrappers
    # under ~/.claude/hooks/source_of_truth_*_hook.py. We are about to
    # replace them with proper install-dir entries.
    removed_old_user_count = remove_hook_entries_matching_substrings(
        settings_data, "UserPromptSubmit", OLD_LOOSE_WRAPPER_MARKER_SUBSTRINGS
    )
    removed_old_post_count = remove_hook_entries_matching_substrings(
        settings_data, "PostToolUse", OLD_LOOSE_WRAPPER_MARKER_SUBSTRINGS
    )
    if removed_old_user_count + removed_old_post_count:
        print(
            f"  migrated: removed {removed_old_user_count} old UserPromptSubmit "
            f"+ {removed_old_post_count} old PostToolUse loose-wrapper entries"
        )
    # Write backward-compat forwarder stubs at the old loose-wrapper paths so
    # already-running sessions (whose hook config was cached at startup) keep
    # working until they restart.
    write_backward_compat_forwarder_stubs(install_dir)

    # Add our entries (only if not already present pointing at the install dir).
    user_command = f'{python_launcher} "{user_hook_path}"'
    post_command = f'{python_launcher} "{post_hook_path}"'

    settings_was_modified = removed_old_user_count + removed_old_post_count > 0

    if hook_event_already_has_entry_referencing(
        settings_data, "UserPromptSubmit", (NEW_INSTALL_DIR_MARKER_SUBSTRING,)
    ):
        print("  UserPromptSubmit entry already present — no change")
    else:
        append_hook_entry(settings_data, "UserPromptSubmit", "*", user_command)
        print(f"  appended UserPromptSubmit entry: {user_command}")
        settings_was_modified = True

    if hook_event_already_has_entry_referencing(
        settings_data, "PostToolUse", (NEW_INSTALL_DIR_MARKER_SUBSTRING,)
    ):
        print("  PostToolUse entry already present — no change")
    else:
        append_hook_entry(settings_data, "PostToolUse", "Bash", post_command)
        print(f"  appended PostToolUse(matcher=Bash) entry: {post_command}")
        settings_was_modified = True

    if settings_was_modified:
        backup_path = backup_file(settings_path)
        if backup_path:
            print(f"  backed up old settings.json to {backup_path}")
        write_settings_json(settings_path, settings_data)
    else:
        print("  no settings.json changes needed")

    print()
    print("Install complete.")
    print(
        "Open a new Claude Code session. The hooks will silently no-op until you "
        "register that session to a source-of-truth project via:"
    )
    print(f"  {python_launcher} -c 'import sys; sys.path.insert(0, \"{package_dir}\"); from source_of_truth.cli_entrypoint import _main; sys.exit(_main())' init-and-register <session_id> <conversation_path>")
    print(
        "or, if you installed the `sot` shell wrapper:"
    )
    print("  sot init-and-register <session_id> <conversation_path>")


if __name__ == "__main__":
    main()
